
name: 'Setup Workflow'
description: 'Sets up the workflow'
runs:
  using: "composite"
  steps:

  - name: Setup Go 1.20
    uses: actions/setup-go@v3
    with:
      go-version: '^1.20'

  - name: Cache Go Modules
    uses: actions/cache@v3
    with:
      path: |
        ~/.cache/go-build
        ~/go/pkg/mod
      key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      restore-keys: |
        ${{ runner.os }}-go

  - name: Download Go Modules
    shell: bash
    run: go mod download -x