---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
data:
  policy.hcl: |
    path "secret/data/example" {
      capabilities = ["read"]
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-sa
  annotations:
    vault.hashicorp.com/bind: 'true'
    vault.hashicorp.com/configmap-policy: example-configmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
spec:
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: default-example-sa
        vault.hashicorp.com/agent-inject-secret-example: secret/example
    spec:
      serviceAccountName: example-sa
      containers:
      - name: example-app
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - sleep infinity
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
