server:
  extraEnvironmentVars:
    VAULT_CLI_NO_COLOR: '1'
  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
  livenessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true"
    initialDelaySeconds: 60
  ingress:
    enabled: true
    hosts:
    - paths: ["/"]