name: CI
on:
  push:
    branches: [main]
    tags: [v*]
jobs:

  unit-tests:

    name: Unit Tests
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot'
    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19'

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go

    - name: Download Go Modules
      shell: bash
      run: go mod download -x

    - name: Run Static Analysis
      shell: bash
      run: make lint

    - name: Run Unit Tests
      shell: bash
      run: make test

  build:

    name: Build and Publish
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot'
    needs: unit-tests
    env:
      REPO: ghcr.io
      OWNER: tinyzimmer
      PACKAGE_NAME: vault-rbac-controller
      PLATFORMS: linux/amd64,linux/arm64,linux/arm
    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19'

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go

    - name: Download Go Modules
      shell: bash
      run: go mod download -x

    - name: Build Release Binaries
      shell: bash
      run: make dist

    - name: Get Image Tags
      shell: bash
      id: tags
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]] ; then
          echo TAGS=${REPO}/${OWNER}/${PACKAGE_NAME}:latest >> ${GITHUB_OUTPUT}
        else
          echo TAGS=${REPO}/${OWNER}/${PACKAGE_NAME}:latest,${REPO}/${OWNER}/${PACKAGE_NAME}:${{ github.ref_name }} >> ${GITHUB_OUTPUT}
        fi

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REPO }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    -  name: Build and push
       uses: docker/build-push-action@v3
       with:
         push: true
         context: .
         tags: ${{ steps.tags.outputs.TAGS }}
         platforms: ${{ env.PLATFORMS }}

    # - name: Delete untagged images
    #   uses: actions/github-script@v6
    #   env:
    #     PER_PAGE: 100
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     script: |
    #       const response = await github.request("GET /user/packages/container/${{ env.PACKAGE_NAME }}/versions",
    #         { per_page: ${{ env.PER_PAGE }} }
    #       );
    #       for(version of response.data) {
    #           if (version.metadata.container.tags.length == 0) {
    #               console.log("delete " + version.id)
    #               const deleteResponse = await github.request("DELETE /user/packages/container/${{ env.PACKAGE_NAME }}/versions/" + version.id, { });
    #               console.log("status " + deleteResponse.status)
    #           }
    #       }
